### ISSUE TITLE
Only showing Gilly and Ike contracts

### ISSUE THREAD

**Issue by ghost** [jrossignol/ContractPack-RemoteTech#22]
Hi I installed via CKAN, can only see these two contracts...
![screenshot 2017-08-05 16 00 29](https://user-images.githubusercontent.com/14941242/28993339-693f7578-79f7-11e7-9dd8-fa4e13e304c3.png)

**Comment by jrossignol** [comment]
Weird.  Can you get me a KSP.log file?

**Comment by ghost** [comment]
Here's the log:
[KSP.log.txt](https://github.com/jrossignol/ContractPack-RemoteTech/files/1202859/KSP.log.txt)


I have downgraded to the previous release of Contract Configurator (1.23.1) and it seems to work.

**Comment by Machine-Maker** [comment]
I am also having an issue similar where only the contracts for Gilly/Ike and all the moons from Outer Planets Mod. Here is a screenshot of the contracts.
![remotetechcontractsbug](https://user-images.githubusercontent.com/15055071/29237710-ef631296-7ed8-11e7-9d06-3ca06225d718.png)

And here is the KSP.log.
[KSP - Copy.log.txt](https://github.com/jrossignol/ContractPack-RemoteTech/files/1219460/KSP.-.Copy.log.txt)

**Comment by oroussel** [comment]
It seems that's because, in KSP 1.3, the stock partModuleType "Power", used in definition of the contracts, does not exists anymore.
The KSP log has several lines which says:
`[EXC 17:00:18.032] ArgumentException: Stock partModuleType 'Power' has been replaced by 'Generator'.`

Indeed, changing in all the contracts files [`partModuleType = Power`](https://github.com/jrossignol/ContractPack-RemoteTech/blob/master/GameData/ContractPacks/RemoteTech/KerbinRelay.cfg#L201) to `partModuleType = Generator` fixes everything: all contracts are back in the game, no exceptions in the KSP log, and the contracts are working properly.

**Comment by Machine-Maker** [comment]
@oroussel Yes that fixed the issue. Thank You.

**Comment by jrossignol** [comment]
Awesome, thanks for thie @oroussel
